version: '3'
services: 
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=PASSWORD
       - PGDATA=/var/lib/postgresql/data/pgdata
       - POSTGRES_DB=postgres
    volumes:
       - ./Data:/var/lib/postgresql
       - ./Phase1/Dataset/:/srv/soen363/phase1/
    ports:
       - 5432:5432